### ISSUE TITLE
Enhancement request: Menu option to swap joystick ports

### ISSUE THREAD

**Issue by tonedef71** [zeldin/Mega99#6]
I noticed that some cores for the MEGA65 have a menu option to swap joystick ports.  Do you think such an option would be useful for the Mega99 core?

One use case for this feature is when you have two different types of joystick controllers, each one plugged into a different controller port on the MEGA65 simultaneously.  You may be playing a game and later decide that the joystick controller that is plugged into the other port would be more suitable/comfortable for that particular game.  A "Swap Joystick ports" feature would spare you the inconvenience of having to unplug and re-plug the joystick controllers.

**Comment by zeldin** [comment]
Implemented in v1.4
